apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webmin-pvc
  labels:
    app: webmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
